spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/test
    username: root
    password: 1234
jwt:
  secret-key: hello-spring-security-spring-security-with-jwt-1q2w3e4r!-world
  access-token:
    expire-length: 600000
  refresh-token:
    expire-length: 3600000
server:
  servlet:
    encoding:
      force: true
      enabled: true
      charset: UTF-8
